---
# Variables listed here are applicable to all host groups
default_my_ip: "{{ ansible_default_ipv4.address }}"
memcached_host: "{{ default_my_ip }}"

# database and password
database_host: "{{ default_my_ip }}"
neutron_db_password: "{{ lookup('password', inventory_dir + '/.auth/neutron-db-password chars=ascii_letters') }}"
nova_db_password: "{{ lookup('password', inventory_dir + '/.auth/nova-db-password chars=ascii_letters') }}"
cinder_db_password: "{{ lookup('password', inventory_dir + '/.auth/cinder-db-password chars=ascii_letters') }}"
keystone_db_password: "{{ lookup('password', inventory_dir + '/.auth/keystone-db-password chars=ascii_letters') }}"
glance_db_password: "{{ lookup('password', inventory_dir + '/.auth/glance-db-password chars=ascii_letters') }}"

# keystone username & password
keystone_host: "{{ default_my_ip }}"

neutron_os_username: "neutron"
neutron_os_password: "{{ lookup('password', inventory_dir + '/.auth/neutron-os-password chars=ascii_letters') }}"
glance_os_username: "glance"
glance_os_password: "{{ lookup('password', inventory_dir + '/.auth/glance-os-password chars=ascii_letters') }}"
cinder_os_username: "cinder"
cinder_os_password: "{{ lookup('password', inventory_dir + '/.auth/cinder-os-password chars=ascii_letters') }}"
nova_os_username: "nova"
nova_os_password: "{{ lookup('password', inventory_dir + '/.auth/nova-os-password chars=ascii_letters') }}"
nova_placement_username: "placement"
nova_placement_password: "{{ lookup('password', inventory_dir + '/.auth/nova-os-password chars=ascii_letters') }}"

# rabbitmq and password
rabbitmq_host: "{{ default_my_ip }}"
rabbitmq_password: "{{ lookup('password', inventory_dir + '/.auth/rabbitmq-password chars=ascii_letters') }}"

# keystone service & endpoint
nova_host: "{{ default_my_ip }}"
cinder_host: "{{ default_my_ip }}"
glance_host: "{{ default_my_ip }}"
neutron_host: "{{ default_my_ip }}"

keystone_admin_url: "http://{{ keystone_host }}:5000/v3"
keystone_public_url: "http://{{ keystone_host }}:5000/v3"
keystone_internal_url: "http://{{ keystone_host }}:5000/v3"

glance_admin_url: "http://{{ glance_host }}:9292"
glance_public_url: "http://{{ glance_host }}:9292"
glance_internal_url: "http://{{ glance_host }}:9292"

cinder_v2_url: "http://{{ cinder_host }}:8776/v2/%(project_id)s"
cinder_v3_url: "http://{{ cinder_host }}:8776/v3/%(project_id)s"

neutron_public_url: "http://{{ neutron_host }}:9696"

nova_public_url: "http://{{ nova_host }}:8774/v2.1"
placement_public_url: "http://{{ nova_host }}:8778"

# keystone service
keystone_admin_token: "{{ lookup('password', inventory_dir + '/.auth/keystone-admin-token chars=ascii_letters') }}"
keystone_admin_password: "{{ lookup('password', inventory_dir + '/.auth/keystone-admin-password chars=ascii_letters') }}"


# nova & neutron service
metadata_shared_secret: "{{ lookup('password', inventory_dir + '/.auth/metadata-shared-secret chars=ascii_letters') }}"
